version: '3.2'
services:
  database:
    image: mysql:5.7
    ports:
      - "5307:3306"
    volumes:
      - ./database/db:/docker-entrypoint-initdb.d/:ro
      - ./database/data:/var/lib/mysql:rw
    environment:
      - MYSQL_ROOT_PASSWORD=gtp3eAE4CzMcxnYNXTRh
      - MYSQL_USER=plainorm
      - MYSQL_PASSWORD=plainorm
      - MYSQL_DATABASE=plainorm
